import Link from 'next/link';import { StoreArrivalHero } from '@/components/StoreArrivalHero';import { BackButton } from '@/components/BackButton';import { menus, site, stores } from '@/data/site';import { breadcrumbLd, type Crumb } from '@/lib/seo';
export function Header(){return <header className="site-header sticky top-0 z-40"><div className="container flex min-h-20 items-center justify-between gap-6 py-3"><Link href="/" className="brand-sign" aria-label="THE REVENANT トップページ">THE<br/>REVENANT</Link><details className="menu-drawer"><summary aria-label="メニューを開く"><span>MENU</span><span className="menu-bars" aria-hidden="true"><i/><i/><i/></span></summary><nav aria-label="メインナビゲーション"><Link href="/first-time"><small>01</small>初めての方へ</Link><Link href="/menus/coating"><small>02</small>メニュー</Link><Link href="/prices"><small>03</small>料金</Link><Link href="/works"><small>04</small>施工事例</Link><Link href="/blog"><small>05</small>ブログ</Link><Link href="/about"><small>06</small>私たちについて</Link><Link className="nav-contact" href="/contact"><small>07</small>お問い合わせ</Link></nav></details></div></header>}
export function Footer(){return <footer className="site-footer py-12"><div className="container grid gap-5 md:grid-cols-3"><div className="footer-panel footer-brand"><p className="font-serif text-2xl">THE REVENANT</p><p className="mt-3">{site.concept}</p></div>{stores.map(s=><div className="footer-panel" key={s.id}><p className="text-xl font-black">{s.name}</p><p className="mt-2 text-sm">{s.address}</p><p className="text-sm">営業時間 {s.hours}{s.closed?`／定休日 ${s.closed}`:''}</p><Link className="footer-link mt-4 inline-flex" href={s.slug}>店舗ページへ →</Link></div>)}</div><div className="footer-bottom container mt-10 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><nav className="flex flex-wrap items-center gap-x-6 gap-y-2 text-sm font-bold" aria-label="フッターナビゲーション"><Link href="/privacy">プライバシーポリシー</Link><Link href="/sitemap.xml">サイトマップ</Link><a href={site.instagramUrl} target="_blank" rel="noopener noreferrer">Instagram</a></nav><p className="text-xs opacity-80">© {new Date().getFullYear()} {site.name}</p></div></footer>}
export function CTA({title='愛車の状態に合わせて、必要な施工だけを相談できます。'}:{title?:string}){return <section className="section consultation-section"><div className="container"><div className="consultation-card p-8 md:p-12"><p className="eyebrow">PHOTO CONSULTATION</p><h2 className="mt-3 text-3xl font-bold md:text-5xl">{title}</h2><p className="lead mt-4">気になる傷、くすみ、水シミ、納車前後の状態など、まずは写真でお気軽にご相談ください。</p><div className="mt-7 flex flex-wrap gap-3"><Link className="btn btn-primary" href="/contact">愛車の写真を送って相談する</Link><a className="btn btn-sub" href={site.instagramUrl}>Instagramを見る</a></div></div></div></section>}
export function FixedCTA(){return <details className="cta-dial"><summary aria-label="相談メニューを開閉"><span className="cta-dial-plus" aria-hidden="true">＋</span></summary><div className="cta-dial-items"><Link className="cta-dial-item" href="/contact"><svg className="cta-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>写真で相談</Link><a className="cta-dial-item" href="tel:08023965521"><svg className="cta-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.13.96.36 1.9.7 2.81a2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.91.34 1.85.57 2.81.7A2 2 0 0 1 22 16.92z"/></svg>電話する</a><Link className="cta-dial-item" href="/#stores"><svg className="cta-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"/><circle cx="12" cy="10" r="3"/></svg>店舗を選ぶ</Link></div></details>}
export function Hero(){return <StoreArrivalHero/>}
export function MenuGrid(){return <div className="grid gap-5 md:grid-cols-3">{menus.map(m=><Link key={m.slug} href={m.slug} className="card p-6 transition hover:border-bronze"><h3 className="text-xl font-bold">{m.name}</h3><p className="lead mt-3">{m.summary}</p><p className="mt-4 text-sm text-bronze">{m.price}</p></Link>)}</div>}
export function JsonLd({data}:{data:unknown}){return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data)}}/>}
// Visible breadcrumb trail + matching BreadcrumbList structured data. Pass the
// hops after the home root; the current page should be the last crumb.
export function Breadcrumbs({items}:{items:Crumb[]}){const trail=[{name:'ホーム',path:'/'},...items];return <><JsonLd data={breadcrumbLd(items)}/><div className="container pt-6 flex items-center gap-3 flex-wrap"><BackButton/><nav aria-label="パンくずリスト" className="text-sm text-ivory/60"><ol className="flex flex-wrap items-center gap-2">{trail.map((c,i)=>{const last=i===trail.length-1;return <li key={c.path} className="flex items-center gap-2">{last?<span aria-current="page" className="text-ivory/80">{c.name}</span>:<Link className="hover:text-bronze" href={c.path}>{c.name}</Link>}{!last&&<span aria-hidden="true">/</span>}</li>})}</ol></nav></div></>}
