import Link from 'next/link';import { StoreArrivalHero } from '@/components/StoreArrivalHero';import { menus, site, stores } from '@/data/site';import { breadcrumbLd, type Crumb } from '@/lib/seo';
export function Header(){return <header className="site-header sticky top-0 z-40"><div className="container flex min-h-20 items-center justify-between gap-6 py-3"><Link href="/" className="brand-sign" aria-label="THE REVENANT トップページ">THE<br/>REVENANT</Link><details className="menu-drawer"><summary aria-label="メニューを開く"><span>MENU</span><span className="menu-bars" aria-hidden="true"><i/><i/><i/></span></summary><nav aria-label="メインナビゲーション"><Link href="/first-time"><small>01</small>初めての方へ</Link><Link href="/menus/coating"><small>02</small>メニュー</Link><Link href="/prices"><small>03</small>料金</Link><Link href="/works"><small>04</small>施工事例</Link><Link href="/blog"><small>05</small>ブログ</Link><Link href="/about"><small>06</small>私たちについて</Link><Link className="nav-contact" href="/contact"><small>07</small>お問い合わせ</Link></nav></details></div></header>}
export function Footer(){return <footer className="site-footer py-12"><div className="container grid gap-5 md:grid-cols-3"><div className="footer-panel footer-brand"><p className="font-serif text-2xl">THE REVENANT</p><p className="mt-3">{site.concept}</p></div>{stores.map(s=><div className="footer-panel" key={s.id}><p className="text-xl font-black">{s.name}</p><p className="mt-2 text-sm">{s.address}</p><p className="text-sm">{s.hours}</p><Link className="footer-link mt-4 inline-flex" href={s.slug}>店舗ページへ →</Link></div>)}</div><div className="container mt-8 flex flex-wrap gap-5 text-sm font-bold"><Link href="/privacy">プライバシーポリシー</Link><Link href="/sitemap.xml">sitemap.xml</Link><a href={site.instagramUrl}>Instagram</a></div></footer>}
export function CTA({title='愛車の状態に合わせて、必要な施工だけを相談できます。'}:{title?:string}){return <section className="section consultation-section"><div className="container"><div className="consultation-card p-8 md:p-12"><p className="eyebrow">PHOTO CONSULTATION</p><h2 className="mt-3 text-3xl font-bold md:text-5xl">{title}</h2><p className="lead mt-4">気になる傷、くすみ、水シミ、納車前後の状態など、まずは写真でお気軽にご相談ください。</p><div className="mt-7 flex flex-wrap gap-3"><Link className="btn btn-primary" href="/contact">愛車の写真を送って相談する</Link><a className="btn btn-sub" href={site.instagramUrl}>Instagramを見る</a></div></div></div></section>}
export function FixedCTA(){return <Link className="cta-fab md:hidden" href="/contact"><span className="cta-ico" aria-hidden="true">📷</span>写真で相談</Link>}
export function Hero(){return <StoreArrivalHero/>}
export function MenuGrid(){return <div className="grid gap-5 md:grid-cols-3">{menus.map(m=><Link key={m.slug} href={m.slug} className="card p-6 transition hover:border-bronze"><h3 className="text-xl font-bold">{m.name}</h3><p className="lead mt-3">{m.summary}</p><p className="mt-4 text-sm text-bronze">{m.price}</p></Link>)}</div>}
export function JsonLd({data}:{data:unknown}){return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data)}}/>}
// Visible breadcrumb trail + matching BreadcrumbList structured data. Pass the
// hops after the home root; the current page should be the last crumb.
export function Breadcrumbs({items}:{items:Crumb[]}){const trail=[{name:'ホーム',path:'/'},...items];return <><JsonLd data={breadcrumbLd(items)}/><nav aria-label="パンくずリスト" className="container pt-6 text-sm text-ivory/60"><ol className="flex flex-wrap items-center gap-2">{trail.map((c,i)=>{const last=i===trail.length-1;return <li key={c.path} className="flex items-center gap-2">{last?<span aria-current="page" className="text-ivory/80">{c.name}</span>:<Link className="hover:text-bronze" href={c.path}>{c.name}</Link>}{!last&&<span aria-hidden="true">/</span>}</li>})}</ol></nav></>}
